FROM grafana/grafana:latest

# Set default environment variables (these can still be overridden by docker-compose)
#ENV GF_SECURITY_ADMIN_PASSWORD=defaultPassword
#ENV DB_DATABASE=defaultDatabase
#ENV DB_USERNAME=defaultUsername
#ENV WWWUSER=1000
#ENV WWWGROUP=1000

EXPOSE 3000
